spring:
  application:
    name: erp-demo

  jackson:
    time-zone: UTC

  datasource:
    url: jdbc:mysql://localhost:3306/sample_db?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

logging:
  level:
    org:
      springframework:
        security: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE
